<div class="featured-collection">
  <a href="<?php echo $this->getUrl('coming-soon'); ?>">
      <picture>
        <source data-srcset="<?php echo $this->getSkinUrl('images/featured-collection-1.webp'); ?>" type="image/webp">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-srcset="<?php echo $this->getSkinUrl('images/featured-collection-1.png'); ?>" alt="<?php echo $this->__('Bras'); ?>" class="lazyload">
      </picture>
      <h4 class="featured-collection-title"><?php echo $this->__('Bras'); ?></h4>
  </a>

  <a href="<?php echo $this->getUrl('coming-soon'); ?>">
      <picture>
        <source data-srcset="<?php echo $this->getSkinUrl('images/featured-collection-2.webp'); ?>" type="image/webp">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-srcset="<?php echo $this->getSkinUrl('images/featured-collection-2.png'); ?>" alt="<?php echo $this->__('Knickers'); ?>" class="lazyload">
      </picture>
      <h4 class="featured-collection-title"><?php echo $this->__('Knickers'); ?></h4>
  </a>

  <a href="<?php echo $this->getUrl('coming-soon'); ?>">
      <picture>
        <source data-srcset="<?php echo $this->getSkinUrl('images/featured-collection-3.webp'); ?>" type="image/webp">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-srcset="<?php echo $this->getSkinUrl('images/featured-collection-3.png'); ?>" alt="<?php echo $this->__('Sets'); ?>" class="lazyload">
      </picture>
      <h4 class="featured-collection-title"><?php echo $this->__('Sets'); ?></h4>
  </a>

  <a href="<?php echo $this->getUrl('coming-soon'); ?>">
      <picture>
        <source data-srcset="<?php echo $this->getSkinUrl('images/featured-collection-4.webp'); ?>" type="image/webp">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-srcset="<?php echo $this->getSkinUrl('images/featured-collection-4.png'); ?>" alt="<?php echo $this->__('Multipacks'); ?>" class="lazyload">
      </picture>
      <h4 class="featured-collection-title"><?php echo $this->__('Multipacks'); ?></h4>
  </a>

  <?php echo $this->getChildHTML('product-finder'); ?>
</div>