<div class="product-finder">

  <form method="get" action="#" class="product-finder-form">
    <h3 class="product-finder-title"><span><?php echo $this->__('bra'); ?></span><?php echo $this->__('Finder'); ?></h3>
      
    <select name="size">
      <option><?php echo $this->__('Size'); ?></option>
      <option value="1485"><?php echo $this->__('UK 6 (28-30 Bra)'); ?></option>
      <option value="1482"><?php echo $this->__('UK 8 (30-32 Bra)'); ?></option>
      <option value="1480"><?php echo $this->__('UK 10 (32-34 Bra)'); ?></option>
      <option value="1481">UK 12 (34-36 Bra)'); ?></option>
      <option value="1565"><?php echo $this->__('UK 16 (38-40 Bra)'); ?></option>
      <option value="1638"><?php echo $this->__('UK 18 (40-42 Bra)'); ?></option>
      <option value="1544"><?php echo $this->__('28AA'); ?></option>
      <option value="1545"><?php echo $this->__('28A'); ?></option>
      <option value="1546"><?php echo $this->__('28B'); ?></option>
      <option value="1548"><?php echo $this->__('28C'); ?></option>
      <option value="1549"><?php echo $this->__('28D'); ?></option>
      <option value="1451"><?php echo $this->__('30AA'); ?></option>
      <option value="1450"><?php echo $this->__('30A'); ?></option>
      <option value="1541"><?php echo $this->__('30B'); ?></option>
      <option value="1550"><?php echo $this->__('30C'); ?></option>
      <option value="1551"><?php echo $this->__('30D'); ?></option>
      <option value="1448"><?php echo $this->__('32AA'); ?></option>
      <option value="1447"><?php echo $this->__('32A'); ?></option>
      <option value="1446"><?php echo $this->__('32B'); ?></option>
      <option value="1445"><?php echo $this->__('32C'); ?></option>
      <option value="1444"><?php echo $this->__('32D'); ?></option>
      <option value="1442"><?php echo $this->__('34AA'); ?></option>
      <option value="1441"><?php echo $this->__('34A'); ?></option>
      <option value="1440"><?php echo $this->__('34B'); ?></option>
      <option value="1439"><?php echo $this->__('34C'); ?></option>
      <option value="1438"><?php echo $this->__('34D'); ?></option>
      <option value="1436"><?php echo $this->__('36A'); ?></option>
      <option value="1435"><?php echo $this->__('36B'); ?></option>
      <option value="1434"><?php echo $this->__('36C'); ?></option>
      <option value="1433"><?php echo $this->__('36D'); ?></option>
      <option value="1552"><?php echo $this->__('38A'); ?></option>
      <option value="1431"><?php echo $this->__('38B'); ?></option>
      <option value="1430"><?php echo $this->__('38C'); ?></option>
      <option value="1429"><?php echo $this->__('38D'); ?></option>
      <option value="1633"><?php echo $this->__('38DD'); ?></option>
    </select>

    <select name="style">
      <option><?php echo $this->__('Style'); ?></option>
      <option value="1598"><?php echo $this->__('Bandeau'); ?></option>
      <option value="1933"><?php echo $this->__('Cotton'); ?></option>
      <option value="1596"><?php echo $this->__('Crop top'); ?></option>
      <option value="1592"><?php echo $this->__('Lightly padded'); ?></option>
      <option value="1578"><?php echo $this->__('Non-Wired'); ?></option>
      <option value="1590"><?php echo $this->__('Padded'); ?></option>
      <option value="1589"><?php echo $this->__('Push-up'); ?></option>
      <option value="1588"><?php echo $this->__('Racerback'); ?></option>
      <option value="1587"><?php echo $this->__('Sports Bra'); ?></option>
      <option value="1585"><?php echo $this->__('Teen Friendly'); ?></option>
      <option value="1582"><?php echo $this->__('Triangle bra'); ?></option>
      <option value="1579"><?php echo $this->__('Underwired'); ?></option>
      <option value="1581"><?php echo $this->__('Unpadded'); ?></option>
    </select>

    <select name="color">
      <option><?php echo $this->__('Colour'); ?></option>
      <option value="1991"><?php echo $this->__('dresden blue'); ?></option>
      <option value="1995"><?php echo $this->__('Fluro orange'); ?></option>
      <option value="1994"><?php echo $this->__('leopard white'); ?></option>
      <option value="1989"><?php echo $this->__('lime punch'); ?></option>
      <option value="1993"><?php echo $this->__('mallard blue'); ?></option>
      <option value="1990"><?php echo $this->__('vibrant orange'); ?></option>
      <option value="1650"><?php echo $this->__('Wh/blk/red'); ?></option>
      <option value="2015"><?php echo $this->__('white &amp; white spot'); ?></option>
      <option value="24"><?php echo $this->__('Black'); ?></option>
      <option value="1556"><?php echo $this->__('calypso'); ?></option>
      <option value="1664"><?php echo $this->__('Ecru'); ?></option>
      <option value="1750"><?php echo $this->__('fjord'); ?></option>
      <option value="1743"><?php echo $this->__('floral lime print'); ?></option>
      <option value="505"><?php echo $this->__('Flower print'); ?></option>
      <option value="1955"><?php echo $this->__('Frape'); ?></option>
      <option value="22"><?php echo $this->__('Green'); ?></option>
      <option value="293"><?php echo $this->__('Grey marl'); ?></option>
      <option value="1899"><?php echo $this->__('kiwi'); ?></option>
      <option value="1963"><?php echo $this->__('majestic bird'); ?></option>
      <option value="1749"><?php echo $this->__('melange'); ?></option>
      <option value="1887"><?php echo $this->__('mint leaf'); ?></option>
      <option value="1658"><?php echo $this->__('navy blue'); ?></option>
      <option value="1342"><?php echo $this->__('Nude'); ?></option>
      <option value="1339"><?php echo $this->__('Orange'); ?></option>
      <option value="1323"><?php echo $this->__('Pattern'); ?></option>
      <option value="57"><?php echo $this->__('Pink'); ?></option>
      <option value="1900"><?php echo $this->__('pink glo'); ?></option>
      <option value="1333"><?php echo $this->__('Purple'); ?></option>
      <option value="26"><?php echo $this->__('Red'); ?></option>
      <option value="1940"><?php echo $this->__('rose'); ?></option>
      <option value="1661"><?php echo $this->__('sorbet'); ?></option>
      <option value="1937"><?php echo $this->__('stars n stripes'); ?></option>
      <option value="1614"><?php echo $this->__('turquoise'); ?></option>
      <option value="1883"><?php echo $this->__('viola'); ?></option>
      <option value="60"><?php echo $this->__('White'); ?></option>
      <option value="1543"><?php echo $this->__('white &amp; pink/lilac'); ?></option>
      <option value="1539"><?php echo $this->__('white &amp; white/pink'); ?></option>
      <option value="1618"><?php echo $this->__('white/neon'); ?></option>
      <option value="1956"><?php echo $this->__('wineberry'); ?></option>
    </select>

    <button><?php echo $this->__('Find it'); ?></button>
  </form>
</div>