<ul class="footer-links">
	<li><a href="<?php echo $this->getUrl('about-magento-demo-store') ?>"><?php echo $this->__('About us'); ?></a></li>
	<li><a href="<?php echo $this->getUrl('customer-service') ?>"><?php echo $this->__('Customer Services'); ?></a></li>
	<li><a href="<?php echo $this->getUrl('coming-soon') ?>"><?php echo $this->__('Press'); ?></a></li>
	<li><a href="<?php echo $this->getUrl('coming-soon') ?>"><?php echo $this->__('Legal'); ?></a></li>
	<li><a href="<?php echo $this->getUrl('coming-soon') ?>"><?php echo $this->__('Accessibility'); ?></a></li>
	<li><a href="<?php echo $this->getUrl('catalog/seo_sitemap/category') ?>"><?php echo $this->__('Sitemap'); ?></a></li>
</ul>